export const withdrawalQueueAbi = [
  {
    name: "getWithdrawalStatus",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_requestIds", type: "uint256[]" }],
    outputs: [
      {
        name: "statuses",
        type: "tuple[]",
        components: [
          { name: "amountOfStETH", type: "uint256" },
          { name: "amountOfShares", type: "uint256" },
          { name: "owner", type: "address" },
          { name: "timestamp", type: "uint256" },
          { name: "isFinalized", type: "bool" },
          { name: "isClaimed", type: "bool" },
        ],
      },
    ],
  },
  {
    name: "getWithdrawalRequests",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_owner", type: "address" }],
    outputs: [{ name: "requestsIds", type: "uint256[]" }],
  },
  {
    name: "getLastFinalizedRequestId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getClaimableEther",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "_requestIds", type: "uint256[]" },
      { name: "_hints", type: "uint256[]" },
    ],
    outputs: [{ name: "claimableEth", type: "uint256[]" }],
  },
  {
    name: "findCheckpointHints",
    type: "function",
    stateMutability: "view",
    inputs: [
      { name: "_requestIds", type: "uint256[]" },
      { name: "_firstIndex", type: "uint256" },
      { name: "_lastIndex", type: "uint256" },
    ],
    outputs: [{ name: "hintIds", type: "uint256[]" }],
  },
  {
    name: "getLastCheckpointIndex",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "isBunkerModeActive",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "getLastRequestId",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "getLockedEtherAmount",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "unfinalizedRequestNumber",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "unfinalizedStETH",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "bunkerModeSinceTimestamp",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "uint256" }],
  },
  {
    name: "isPaused",
    type: "function",
    stateMutability: "view",
    inputs: [],
    outputs: [{ name: "", type: "bool" }],
  },
  {
    name: "ownerOf",
    type: "function",
    stateMutability: "view",
    inputs: [{ name: "_requestId", type: "uint256" }],
    outputs: [{ name: "", type: "address" }],
  },
  {
    name: "claimWithdrawal",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [{ name: "_requestId", type: "uint256" }],
    outputs: [],
  },
  {
    name: "claimWithdrawalsTo",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_requestIds", type: "uint256[]" },
      { name: "_hints", type: "uint256[]" },
      { name: "_recipient", type: "address" },
    ],
    outputs: [],
  },
  {
    name: "requestWithdrawalsWstETH",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_amounts", type: "uint256[]" },
      { name: "_owner", type: "address" },
    ],
    outputs: [{ name: "requestIds", type: "uint256[]" }],
  },
  {
    name: "approve",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_to", type: "address" },
      { name: "_requestId", type: "uint256" },
    ],
    outputs: [],
  },
  {
    name: "setApprovalForAll",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_operator", type: "address" },
      { name: "_approved", type: "bool" },
    ],
    outputs: [],
  },
  {
    name: "transferFrom",
    type: "function",
    stateMutability: "nonpayable",
    inputs: [
      { name: "_from", type: "address" },
      { name: "_to", type: "address" },
      { name: "_requestId", type: "uint256" },
    ],
    outputs: [],
  },
] as const;
